server:
  port: 9001

spring:
  application:
    name: BuilderJPA
  datasource:
    url: jdbc:h2:file:~/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
http:
  mappers:
    jsonPrettyPrint: true